"""Category normalization and SF Symbol mapping.

Ported from alities-engine CategoryMap.swift.
"""

# 40-entry alias → canonical name map
ALIAS_TO_CANONICAL: dict[str, str] = {
    "science": "Science & Nature",
    "science & nature": "Science & Nature",
    "nature": "Science & Nature",
    "animals": "Science & Nature",
    "science - computers": "Technology",
    "science - gadgets": "Technology",
    "technology": "Technology",
    "mathematics": "Mathematics",
    "science - mathematics": "Mathematics",
    "history": "History",
    "geography": "Geography",
    "politics": "Politics",
    "sports": "Sports",
    "sport_and_leisure": "Sports",
    "music": "Music",
    "musicals & theatres": "Music",
    "literature": "Literature",
    "books": "Literature",
    "arts_and_literature": "Arts & Literature",
    "arts and literature": "Arts & Literature",
    "art": "Arts & Literature",
    "movies": "Film & TV",
    "film": "Film & TV",
    "film_and_tv": "Film & TV",
    "television": "Film & TV",
    "cartoon & animations": "Film & TV",
    "japanese anime & manga": "Film & TV",
    "video games": "Video Games",
    "board games": "Board Games",
    "comics": "Comics",
    "food & drink": "Food & Drink",
    "food_and_drink": "Food & Drink",
    "pop culture": "Pop Culture",
    "celebrities": "Pop Culture",
    "mythology": "Mythology",
    "society_and_culture": "Society & Culture",
    "society and culture": "Society & Culture",
    "general_knowledge": "General Knowledge",
    "general knowledge": "General Knowledge",
    "vehicles": "Vehicles",
    "romance novels": "Romance Novels",
    "silent movies": "Silent Movies",
    "broadway musicals": "Broadway Musicals",
    "broadway": "Broadway Musicals",
    "cocktails & spirits": "Cocktails & Spirits",
    "cocktails": "Cocktails & Spirits",
    "space exploration": "Space Exploration",
    "true crime": "True Crime",
    "fashion & design": "Fashion & Design",
    "fashion": "Fashion & Design",
    "roller coasters": "Roller Coasters",
    "theme parks": "Roller Coasters",
    "animated films": "Animated Films",
    "animation": "Animated Films",
    "chess": "Chess",
    "national parks": "National Parks",
    "horror movies": "Horror Movies",
    "horror": "Horror Movies",
    "the beatles": "The Beatles",
    "beatles": "The Beatles",
    "inventions": "Inventions",
    "reality tv": "Reality TV",
    "volcanoes & earthquakes": "Volcanoes & Earthquakes",
    "volcanoes": "Volcanoes & Earthquakes",
    "stand-up comedy": "Stand-Up Comedy",
    "standup": "Stand-Up Comedy",
    "pirates & smugglers": "Pirates & Smugglers",
    "pirates": "Pirates & Smugglers",
    "olympic games": "Olympic Games",
    "olympics": "Olympic Games",
    "candy & chocolate": "Candy & Chocolate",
    "candy": "Candy & Chocolate",
    "chocolate": "Candy & Chocolate",
}

# 20-entry canonical name → SF Symbol map
CANONICAL_TO_SYMBOL: dict[str, str] = {
    "Science & Nature": "atom",
    "Technology": "desktopcomputer",
    "Mathematics": "number",
    "History": "clock",
    "Geography": "globe.americas",
    "Politics": "building.columns",
    "Sports": "sportscourt",
    "Music": "music.note",
    "Literature": "book",
    "Arts & Literature": "paintbrush",
    "Film & TV": "film",
    "Video Games": "gamecontroller",
    "Board Games": "gamecontroller",
    "Comics": "text.bubble",
    "Food & Drink": "fork.knife",
    "Pop Culture": "star",
    "Mythology": "sparkles",
    "Society & Culture": "person.3",
    "General Knowledge": "questionmark.circle",
    "Vehicles": "car",
    "Romance Novels": "heart.text.square",
    "Silent Movies": "film.stack",
    "Broadway Musicals": "theatermasks",
    "Cocktails & Spirits": "wineglass",
    "Space Exploration": "airplane.departure",
    "True Crime": "magnifyingglass",
    "Fashion & Design": "tshirt",
    "Roller Coasters": "figure.roller.coaster",
    "Animated Films": "wand.and.stars",
    "Chess": "crown",
    "National Parks": "mountain.2",
    "Horror Movies": "eye.trianglebadge.exclamationmark",
    "The Beatles": "music.mic",
    "Inventions": "lightbulb",
    "Reality TV": "tv",
    "Volcanoes & Earthquakes": "flame",
    "Stand-Up Comedy": "mic",
    "Pirates & Smugglers": "sailboat",
    "Olympic Games": "medal",
    "Candy & Chocolate": "birthday.cake",
}

CANONICAL_CATEGORIES: list[str] = list(CANONICAL_TO_SYMBOL.keys())


def normalize(raw: str) -> str:
    """Map a raw category string to its canonical name."""
    return ALIAS_TO_CANONICAL.get(raw.lower().strip(), raw)


def symbol_for(category: str) -> str:
    """Return the SF Symbol name for a category (canonical or alias)."""
    canonical = normalize(category)
    return CANONICAL_TO_SYMBOL.get(canonical, "questionmark.circle")
